version: "3.9"
services:
  auth_service:
    build:
      context: .
    container_name: auth_service
    ports:
      - "6080:6080"
    restart: always
    environment:
      KANJI_AUTH_GRPC_ADDRESS: ":6080"
      KANJI_AUTH_POSTGRES_NAME: "auth"
      KANJI_AUTH_POSTGRES_HOST: "db"
      KANJI_AUTH_POSTGRES_PORT: 5432
      KANJI_AUTH_POSTGRES_USER: "user"
      KANJI_AUTH_USER_ADDRESS: "user:5000"
      KANJI_AUTH_POSTGRES_PASSWORD: "password"
      KANJI_AUTH_JWT_SECRET_KEY: "somekey"
      KANJI_AUTH_MIGRATIONS_SOURCE_URL: "file://migrations"
    depends_on:
      - db
  user_service:
    build:
      context: ../user
    container_name: user_service
    ports:
      - "5000:5000"
    restart: always
    environment:
      KANJI_USER_GRPC_ADDRESS: ":5000"
      KANJI_USER_POSTGRES_NAME: "user"
      KANJI_USER_POSTGRES_HOST: "db"
      KANJI_USER_POSTGRES_PORT: 5432
      KANJI_USER_POSTGRES_USER: "user"
      KANJI_USER_POSTGRES_PASSWORD: "password"
      KANJI_USER_JWT_SECRET_KEY: "somekey"
      KANJI_USER_MIGRATIONS_SOURCE_URL: "file://migrations"
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
